### ISSUE TITLE
detect overylay touch

### ISSUE THREAD

**Issue by evrenios** [jcmore2/BannerTime#1]
hello how can i detect if user clicked on the overlay

**Comment by jcmore2** [comment]
Hi,

Currently, when the dialog is created setCanceledOnTouchOutside is false by default

dialog.setCanceledOnTouchOutside (false);

so it might be a good idea to be a developer option. I will work on it.

**Comment by jcmore2** [comment]
Solved in new version 1.0.1 using  setTouchOverlay()  method.
