### ISSUE TITLE
decreasing the min sdk version from 14 to 10

### ISSUE THREAD

**Issue by evrenios** [jcmore2/BannerTime#2]
Hello, is it possible to make minSdkVersion 14 to minSdkVersion 10

Thanks in advance

**Comment by jcmore2** [comment]
Hi!

Sure, I think I´m not using anything that isn´t incompatible. I will do it!

**Comment by mderinkok** [comment]
Hi @jcmore2, I am struggling with the same problem. When do you think it will be done?

**Comment by jcmore2** [comment]
It is already updated in version 1.1.0

**Comment by mderinkok** [comment]
Thank you very much!
